### ISSUE TITLE
Do you need some help with the plugin?

### ISSUE THREAD

**Issue by tamtamchik** [modcloth/newrelic_rabbitmq_plugin#8]
Hi, @jszwedko thanks for this plugin, I recently came across and wrapped it into docker image (https://hub.docker.com/r/tamtamchik/newrelic-rabbitmq/).

I see that the last update was done 3 years ago, but there are some issues and PR. 
Do you plan to continue support of this plugin, or you need some help?

**Comment by jszwedko** [comment]
Hi @tamtamchik,

Nice, I like that. Unfortunately, I no longer have access to this repository, but I encourage @jjeb to consider transferring ownership to you. I no longer use RabbitMQ or New Relic so I am probably not the best candidate for continued maintenance.
